from datetime import datetime


class Job:

    def __init__(self):
        self.name = None
        self.src = None
        self.dst = None
        self.notifications = None
        self.twoway = None
        self.enabled = None
        self.script_path = None
        self.days = None
        self.hour = None
        self.minute = None

    def save(self):
        command = f"# generated by pyserversync at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} do not edit manually\n\n"
        command += f"rsync -a {self.src} {self.dst}\n"
        if self.twoway:
            command += f"rsync -a {self.dst} {self.src}\n"

        if self.notifications:
            command += f'notify-send "pyserversync" "{self.name} done!"\n'

        with open(f".pyserversync_jobs/{self.name}.sh", "w") as f:
            f.write(command)
